### ISSUE TITLE
Can I run my own custom graphqlzero on my local server?

### ISSUE THREAD

**Issue by Giorat** [ealmansi/graphqlzero#2]
Can I run my own custom graphqlzero on my local server?

How can I specify my custom Json file to create the server?

**Comment by ealmansi** [comment]
Hi @Giorat ,

The easiest way to run graphqlzero locally is to simply run:

```
npx graphqlzero
# 🚀 GraphQLZero: server ready at http://localhost:4000/.
```

Things that are not currently supported but will be supported soon:

- Customizing the port (currently 4000).
- Setting up you own custom json file.

No ETA at this point, but I'm looking forward to reaching feature parity with json-server asap.

PR's welcome!

**Comment by ealmansi** [comment]
@Giorat , just an update.

You can now customize the port as well. For example:

```
graphqlzero -p 3434
# 🚀 GraphQLZero: server ready at http://localhost:3434/.
```
