### ISSUE TITLE
Problem with Albums and Photos options

### ISSUE THREAD

**Issue by nedko-slavov** [ealmansi/graphqlzero#33]
These two queries stopped work with options:
<img width="1788" alt="Screenshot 2021-04-22 at 11 57 32" src="https://user-images.githubusercontent.com/4362680/115687058-77fb1c00-a362-11eb-9836-8403f31f11b8.png">
<img width="1792" alt="Screenshot 2021-04-22 at 11 57 58" src="https://user-images.githubusercontent.com/4362680/115687063-79c4df80-a362-11eb-9e50-201958879821.png">

**Comment by ImLuze** [comment]
This project uses [jsonplaceholder](https://jsonplaceholder.typicode.com) behind the scenes. That website is currently down for some reason. Everything should be up and running again as soon as that gets resolved.

**Comment by ealmansi** [comment]
Hi @nedko-slavov , it should be working again now.

Apologies for the inconvenience and thanks for your report.
