### ISSUE TITLE
Copy to clipboard always copying for user(id:1)

### ISSUE THREAD

**Issue by anujaykumar1** [ealmansi/graphqlzero#75]
On clicking copy to clipboard it is always copying for the `post` graph but not for the `posts` did not tested for other APIs.

![image](https://user-images.githubusercontent.com/7784343/196981935-74ef644a-3757-4655-85e9-bf4b933b72af.png)

**Comment by ealmansi** [comment]
I cannot reproduce the issue
If you're still experiencing this, please reopen with more details on how to reproduce the issue :pray:
