### ISSUE TITLE
Api seems to be down

### ISSUE THREAD

**Issue by jbaubree** [ealmansi/graphqlzero#81]
Hi @ealmansi,
i think there is an issue with your app actually.
Results are always `Oops. Something went wrong.` in your website.
<img width="733" alt="Capture d’écran 2023-06-26 à 12 14 14" src="https://github.com/ealmansi/graphqlzero/assets/50230578/21806459-59e7-4b3f-b7d4-a3ecde4fd7ce">

**Comment by ealmansi** [comment]
@jbaubree thanks a lot for reporting this :1st_place_medal: 

the API and website should be working normally again now.

please, let me know if you have any further issues :pray:
