### ISSUE TITLE
Example in browser console doesn't work

### ISSUE THREAD

**Issue by kayx23** [ealmansi/graphqlzero#91]
Source: https://graphqlzero.almansi.me/#example-top

Trying this example in the browser console:
![image](https://github.com/ealmansi/graphqlzero/assets/39619599/51a7d80d-cfc0-410f-80d5-3f8d46be6b6f)

i got
![image](https://github.com/ealmansi/graphqlzero/assets/39619599/481758be-32cd-45e7-908d-5da902c1c19b)

Please advise.

**Comment by kayx23** [comment]
Sent a request with bash to confirm the API does work:

```bash
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{ "query": "{ user(id: 1) { id name } }" }' \
  https://graphqlzero.almansi.me/api

{"data":{"user":{"id":"1","name":"Leanne Graham"}}}
```

**Comment by ealmansi** [comment]
it's currently working; it was most likely a connectivity issue or some transient downtime
please, feel free to reopen the issue if you can still reproduce this and we'll investigate further
